COMPANY_SEEDS = (
    {"company_name": "StoreShift", "website_url": "https://storeshift.io", "careers_url": None},
    {"company_name": "Dream Monks", "website_url": "https://dreammonks.com", "careers_url": "https://dreammonks.com/careers"},
    {"company_name": "Tvaram", "website_url": "https://tvaram.com", "careers_url": None},
    {"company_name": "Convertly", "website_url": "https://convertlytechnologies.com", "careers_url": "https://convertlytechnologies.com/careers"},
    {"company_name": "PairNova", "website_url": "https://pairnova.in", "careers_url": None},
    {"company_name": "SkillsCapital", "website_url": "https://skillscapital.io", "careers_url": "https://skillscapital.io/careers"},
    {"company_name": "Velaris Intelligence", "website_url": "https://velarisintelligence.in", "careers_url": "https://velarisintelligence.in/careers"},
    {
        "company_name": "Merkle Science",
        "website_url": "https://www.merklescience.com",
        "careers_url": "https://jobs.lever.co/merklescience",
    },
    {
        "company_name": "Drivetrain",
        "website_url": "https://www.drivetrain.ai",
        "careers_url": "https://jobs.lever.co/drivetrain",
    },
    {
        "company_name": "FamPay",
        "website_url": "https://www.famapp.in",
        "careers_url": "https://jobs.lever.co/fampay",
    },
    {"company_name": "Stellanex", "website_url": "https://www.stellanex.com", "careers_url": None},
    {"company_name": "Supermemory", "website_url": "https://supermemory.ai", "careers_url": None},
    {"company_name": "Path To PR", "website_url": "https://pathtopr.com", "careers_url": "https://pathtopr.com/careers"},
    {"company_name": "Wumn", "website_url": "https://www.wumn.in", "careers_url": None},
    {
        "company_name": "Auxia",
        "website_url": "https://www.auxia.io",
        "careers_url": "https://jobs.lever.co/auxia",
    },
    {"company_name": "Elements Energy", "website_url": "https://elementsenergy.in", "careers_url": "https://elementsenergy.in/careers"},
    {"company_name": "AVEA Technologies", "website_url": "https://aveatechnologies.com", "careers_url": "https://aveatechnologies.com/careers"},
    {"company_name": "Skillzenloop", "website_url": "https://www.skillzenloop.com", "careers_url": None},
    {"company_name": "Xyzon Innovations", "website_url": "https://xyzon.in", "careers_url": None},
    {"company_name": "Deep22 AI", "website_url": "https://deep22.ai", "careers_url": None},
    {"company_name": "Procindex", "website_url": "https://procindex.com", "careers_url": "https://procindex.com/careers"},
    {"company_name": "CredX", "website_url": "https://credx.ai", "careers_url": "https://credx.ai/careers"},
    {"company_name": "aion", "website_url": "https://aiontech.ai", "careers_url": "https://aiontech.ai/careers"},
    {"company_name": "Ciroos", "website_url": "https://ciroos.ai", "careers_url": "https://ciroos.ai/careers/"},
    {"company_name": "Coffee Core", "website_url": "https://coffeecore.in", "careers_url": "https://coffeecore.in/careers"},
    {"company_name": "Appening Infotech", "website_url": "https://appening.co", "careers_url": "https://appening.co/blog/careers/"},
    {"company_name": "Skedler", "website_url": "https://www.guidanz.com", "careers_url": "https://www.guidanz.com/software-engineer-intern/"},
    {"company_name": "Guidanz", "website_url": "https://www.guidanz.com", "careers_url": "https://www.guidanz.com/software-engineer-intern/"},
    {"company_name": "LedgersCFO", "website_url": "https://ledgers.cloud", "careers_url": None},
    {"company_name": "Shoppeal Tech", "website_url": "https://shoppealtech.com", "careers_url": "https://shoppealtech.com/careers"},
    {"company_name": "Growati", "website_url": "https://growati.com", "careers_url": "https://growati.com/careers"},
    {"company_name": "Curer", "website_url": "https://curer.in", "careers_url": "https://curer.in/careers"},
    {"company_name": "THYNE", "website_url": "https://thyne.in", "careers_url": "https://thyne.in/careers"},
    {"company_name": "Tecell", "website_url": "https://tecell.in", "careers_url": "https://careers.tecell.in/jobs/careers"},
    {"company_name": "OutMarket AI", "website_url": "https://outmarket.ai", "careers_url": "https://outmarket.ai/careers"},
    {"company_name": "Monkh AI", "website_url": "https://monkhai.com", "careers_url": "https://monkhai.com/careers"},
    {"company_name": "MHTECHIN", "website_url": "https://mhtechin.com", "careers_url": "https://careers.mhtechin.com/"},
    {"company_name": "Techplement", "website_url": "https://techplement.com", "careers_url": None},
    {"company_name": "CryptoChakra", "website_url": "https://cryptochakra.com", "careers_url": "https://cryptochakra.com/careers"},
    {"company_name": "Truvant Consulting", "website_url": "https://www.truvantconsulting.com", "careers_url": "https://www.truvantconsulting.com/careers"},
    {"company_name": "Ritual", "website_url": "https://ritual.com", "careers_url": "https://jobs.lever.co/ritual"},
    {"company_name": "AapKaPainter", "website_url": "https://aapkapainter.com", "careers_url": "https://aapkapainter.com/careers"},
    {"company_name": "Abstrabit Technologies", "website_url": "https://www.abstrabit.com", "careers_url": "https://www.abstrabit.com/careers"},
    {"company_name": "Datasutram", "website_url": "https://datasutram.com", "careers_url": None},
    {"company_name": "Enterpret", "website_url": "https://www.enterpret.com", "careers_url": None},
    {"company_name": "H2LooP AI", "website_url": "https://h2loop.ai", "careers_url": "https://h2loop.ai/careers"},
    {"company_name": "Atobic", "website_url": "https://atobic.com", "careers_url": "https://atobic.com/careers"},
    {"company_name": "Flexday", "website_url": "https://flexday.ai", "careers_url": "https://flexday.ai/careers"},
    {"company_name": "Pennep", "website_url": "https://pennep.com", "careers_url": "https://pennep.com/careers"},
    {"company_name": "LimeChat", "website_url": "https://limechat.ai", "careers_url": None},
    {"company_name": "Cardboard", "website_url": "https://www.usecardboard.com", "careers_url": "https://www.usecardboard.com/careers"},
    {"company_name": "Optifye.ai", "website_url": "https://optifye.ai", "careers_url": "https://optifye.ai/careers"},
    {"company_name": "Raven", "website_url": "https://raven.dev", "careers_url": "https://raven.dev/careers"},
    {"company_name": "Retape", "website_url": "https://retape.ai", "careers_url": "https://retape.ai/careers"},
    {"company_name": "Paasa", "website_url": "https://paasa.com", "careers_url": "https://paasa.com/careers"},
    {"company_name": "xPay", "website_url": "https://xpaycheckout.com", "careers_url": "https://xpaycheckout.com/careers"},
    {"company_name": "ClickPe", "website_url": "https://clickpe.ai", "careers_url": "https://clickpe.ai/careers"},
    {"company_name": "Rivia.ai", "website_url": "https://rivia.ai", "careers_url": "https://jobs.ashbyhq.com/rivia.ai"},
    {"company_name": "Nxtlogic Software Solutions", "website_url": "https://www.nxtlogic.com", "careers_url": "https://www.nxtlogic.com/careers"},
    {"company_name": "Bimaplan", "website_url": "https://bimaplan.co", "careers_url": "https://bimaplan.co/careers"},
    {"company_name": "Nvron Life Science Software", "website_url": "https://nvronlifescience.com", "careers_url": "https://nvronlifescience.com/careers"},
    {"company_name": "Rechitta", "website_url": "https://rechitta.com", "careers_url": "https://rechitta.com/careers"},
    {"company_name": "Idevify Solutions", "website_url": "https://idevifysolutions.com", "careers_url": "https://idevifysolutions.com/careers"},
    {"company_name": "Crossing Infotech", "website_url": "https://crossinginfotech.com", "careers_url": "https://crossinginfotech.com/careers"},
    {"company_name": "Omninext Technologies", "website_url": "https://omninext.in", "careers_url": "https://omninext.in/careers"},
    {"company_name": "Best Deal Paisa", "website_url": "https://bestdealpaisa.com", "careers_url": "https://bestdealpaisa.com/careers"},
    {"company_name": "Agrani", "website_url": "https://agranilabs.com", "careers_url": "https://agranilabs.com/careers"},
    {"company_name": "NimbleBox.ai", "website_url": "https://nimblebox.ai", "careers_url": None},
    {"company_name": "Zoko", "website_url": "https://www.zoko.io", "careers_url": None},
    {"company_name": "Sprinto", "website_url": "https://sprinto.com", "careers_url": "https://jobs.lever.co/Sprinto"},
    {"company_name": "Rocketlane", "website_url": "https://rocketlane.com", "careers_url": None},
    {"company_name": "Zluri", "website_url": "https://www.zluri.com", "careers_url": "https://zluri.keka.com/careers/"},
    {"company_name": "Facets.cloud", "website_url": "https://facets.cloud", "careers_url": "https://facets.cloud/careers"},
    {"company_name": "CloudSEK", "website_url": "https://cloudsek.com", "careers_url": "https://job-boards.greenhouse.io/cloudsek"},
    {"company_name": "HyperVerge", "website_url": "https://hyperverge.co", "careers_url": "https://hyperverge.co/careers/"},
    {"company_name": "Signzy", "website_url": "https://signzy.com", "careers_url": "https://signzy.keka.com/careers"},
    {"company_name": "Leegality", "website_url": "https://www.leegality.com", "careers_url": "https://careers.leegality.com"},
    {"company_name": "SpotDraft", "website_url": "https://www.spotdraft.com", "careers_url": "https://spotdraft.freshteam.com/jobs"},
    {"company_name": "Entropik", "website_url": "https://www.entropik.io", "careers_url": "https://apply.workable.com/entropik/"},
    {"company_name": "Observe.AI", "website_url": "https://www.observe.ai", "careers_url": "https://job-boards.greenhouse.io/observeai"},
    {"company_name": "Unlearn AI", "website_url": "https://www.unlearn.ai", "careers_url": "https://jobs.ashbyhq.com/unlearn.ai"},
    {"company_name": "SigTuple", "website_url": "https://sigtuple.com", "careers_url": None},
    {"company_name": "Niramai", "website_url": "https://niramai.com", "careers_url": "https://niramai.com/careers/"},
    {"company_name": "CoRover", "website_url": "https://corover.ai", "careers_url": "https://corover.ai/company/careers"},
    {"company_name": "Miko", "website_url": "https://miko.ai", "careers_url": None},
    {"company_name": "Unbox Robotics", "website_url": "https://unboxrobotics.com", "careers_url": "https://unboxrobotics.com/careers"},
    {"company_name": "Ati Motors", "website_url": "https://atirobotics.ai", "careers_url": "https://atirobotics.ai/company/careers/"},
    {"company_name": "Detectify", "website_url": "https://detectify.com", "careers_url": "https://careers.detectify.com"},
    {"company_name": "Securden", "website_url": "https://www.securden.com", "careers_url": "https://www.securden.com/careers/index.html"},
    {"company_name": "Agnikul Cosmos", "website_url": "https://agnikul.in", "careers_url": "https://agnikul.zohorecruit.in/jobs/Careers"},
    {"company_name": "Skyroot Aerospace", "website_url": "https://www.skyroot.in", "careers_url": "https://www.skyroot.in/careers"},
    {"company_name": "Pixxel", "website_url": "https://www.pixxel.space", "careers_url": "https://www.pixxel.space/careers"},
    {"company_name": "Sarvam AI", "website_url": "https://www.sarvam.ai", "careers_url": "https://www.sarvam.ai/careers"},
    {"company_name": "Krutrim", "website_url": "https://www.olakrutrim.com", "careers_url": "https://www.olakrutrim.com/careers"},
    {"company_name": "Pepper Content", "website_url": "https://www.pepper.inc", "careers_url": "https://peppercontent-talent.freshteam.com/jobs"},
    {"company_name": "Airmeet", "website_url": "https://www.airmeet.com", "careers_url": None},
    {"company_name": "WebEngage", "website_url": "https://webengage.com", "careers_url": "https://webengage.com/current-openings/"},
    {"company_name": "MoEngage", "website_url": "https://www.moengage.com", "careers_url": "https://www.moengage.com/careers/"},
    {"company_name": "InVideo", "website_url": "https://invideo.io", "careers_url": None},
    {"company_name": "Classplus", "website_url": "https://classplusapp.com", "careers_url": "https://classplusapp.com/careers"},
    {"company_name": "Teachmint", "website_url": "https://teachmint.com", "careers_url": "https://teachmint.keka.com/careers/"},
    {"company_name": "Newton School", "website_url": "https://www.newtonschool.co", "careers_url": "https://careers.newtonschool.co/newtonschool/"},
    {"company_name": "Unstop", "website_url": "https://unstop.com", "careers_url": None},
    {"company_name": "Nua", "website_url": "https://nuawoman.com", "careers_url": "https://nuawoman.com/careers"},
    {"company_name": "Plum", "website_url": "https://www.plumhq.com", "careers_url": "https://www.plumhq.com/careers"},
    {"company_name": "Rupeek", "website_url": "https://rupeek.com", "careers_url": "https://rupeek.com/careers"},
    {"company_name": "Setu", "website_url": "https://setu.co", "careers_url": None},
    {"company_name": "Cashfree Payments", "website_url": "https://www.cashfree.com", "careers_url": "https://www.cashfree.com/careers/"},
    {"company_name": "Open", "website_url": "https://open.money", "careers_url": None},
    {"company_name": "Fi", "website_url": "https://fi.money", "careers_url": None},
    {"company_name": "Jupiter", "website_url": "https://jupiter.money", "careers_url": "https://jupiter.money/careers/"},
    {"company_name": "Khatabook", "website_url": "https://khatabook.com", "careers_url": "https://khatabook.com/hiring/"},
    {"company_name": "Apna", "website_url": "https://apna.co", "careers_url": None},
    {"company_name": "BlackBuck", "website_url": "https://blackbuck.com", "careers_url": None},
    {"company_name": "Ninjacart", "website_url": "https://ninjacart.com", "careers_url": "https://ninjacart.freshteam.com/jobs"},
    {"company_name": "Locus", "website_url": "https://locus.sh", "careers_url": "https://locus.sh/careers/"},
    {"company_name": "Porter", "website_url": "https://porter.in", "careers_url": None},
    {"company_name": "Shiprocket", "website_url": "https://www.shiprocket.in", "careers_url": None},
    {"company_name": "Ather Energy", "website_url": "https://www.atherenergy.com", "careers_url": "https://careers.atherenergy.com/jobs"},
    {"company_name": "Rapido", "website_url": "https://rapido.bike", "careers_url": None},
    # Additional Indian companies
    {"company_name": "Zoho", "website_url": "https://www.zoho.com", "careers_url": "https://careers.zoho.com/portal/zoho/ShowJobPostings"},
    {"company_name": "Freshworks", "website_url": "https://www.freshworks.com", "careers_url": "https://careers.freshworks.com/jobs"},
    {"company_name": "Chargebee", "website_url": "https://www.chargebee.com", "careers_url": "https://jobs.lever.co/chargebee"},
    {"company_name": "CleverTap", "website_url": "https://clevertap.com", "careers_url": "https://clevertap.com/careers/"},
    {"company_name": "Netcore Cloud", "website_url": "https://netcorecloud.com", "careers_url": "https://netcorecloud.com/careers/"},
    {"company_name": "Exotel", "website_url": "https://exotel.com", "careers_url": "https://exotel.com/careers/"},
    {"company_name": "BrowserStack", "website_url": "https://www.browserstack.com", "careers_url": "https://www.browserstack.com/careers"},
    {"company_name": "Postman", "website_url": "https://www.postman.com", "careers_url": "https://www.postman.com/company/careers/"},
    {"company_name": "Darwinbox", "website_url": "https://darwinbox.com", "careers_url": "https://darwinbox.com/careers"},
    {"company_name": "LambdaTest", "website_url": "https://www.lambdatest.com", "careers_url": "https://www.lambdatest.com/careers"},
    {"company_name": "Zipy", "website_url": "https://zipy.ai", "careers_url": "https://zipy.ai/careers"},
    {"company_name": "Middleware", "website_url": "https://middleware.io", "careers_url": "https://middleware.io/careers"},
    {"company_name": "Requestly", "website_url": "https://requestly.io", "careers_url": "https://requestly.io/careers"},
    {"company_name": "DronaHQ", "website_url": "https://www.dronahq.com", "careers_url": "https://www.dronahq.com/careers/"},
    {"company_name": "Appsmith", "website_url": "https://www.appsmith.com", "careers_url": "https://jobs.lever.co/appsmith"},
    {"company_name": "ToolJet", "website_url": "https://www.tooljet.com", "careers_url": "https://www.tooljet.com/careers"},
    {"company_name": "Novu", "website_url": "https://novu.co", "careers_url": "https://jobs.ashbyhq.com/novu"},
    {"company_name": "Yellow.ai", "website_url": "https://yellow.ai", "careers_url": "https://yellow.ai/careers/"},
    {"company_name": "Haptik", "website_url": "https://www.haptik.ai", "careers_url": "https://www.haptik.ai/careers"},
    {"company_name": "Mad Street Den", "website_url": "https://www.madstreetden.com", "careers_url": "https://www.madstreetden.com/careers"},
    {"company_name": "Gnani.ai", "website_url": "https://gnani.ai", "careers_url": "https://gnani.ai/careers/"},
    {"company_name": "E2E Networks", "website_url": "https://www.e2enetworks.com", "careers_url": "https://www.e2enetworks.com/career"},
    {"company_name": "Neysa", "website_url": "https://neysa.ai", "careers_url": "https://neysa.ai/careers"},
    {"company_name": "Internshala", "website_url": "https://internshala.com", "careers_url": "https://internshala.com/careers"},
    {"company_name": "Delhivery", "website_url": "https://www.delhivery.com", "careers_url": "https://www.delhivery.com/careers"},
    {"company_name": "BlackBuck", "website_url": "https://blackbuck.com", "careers_url": "https://blackbuck.com/careers"},
    {"company_name": "ElasticRun", "website_url": "https://elasticrun.in", "careers_url": "https://elasticrun.in/careers"},
    {"company_name": "Cult.fit", "website_url": "https://www.cult.fit", "careers_url": "https://www.cult.fit/cultfit/careers"},
    {"company_name": "HealthifyMe", "website_url": "https://www.healthifyme.com", "careers_url": "https://apply.workable.com/healthifyme/"},
    {"company_name": "Pristyn Care", "website_url": "https://www.pristyncare.com", "careers_url": "https://www.pristyncare.com/careers/"},
    {"company_name": "Practo", "website_url": "https://www.practo.com", "careers_url": "https://careers.practo.com"},
    {"company_name": "PharmEasy", "website_url": "https://pharmeasy.in", "careers_url": "https://pharmeasy.in/careers/"},
    {"company_name": "Nykaa", "website_url": "https://www.nykaa.com", "careers_url": "https://jobs.nykaa.com/careers"},
    {"company_name": "Meesho", "website_url": "https://meesho.com", "careers_url": "https://meesho.io/careers"},
    {"company_name": "Lenskart", "website_url": "https://www.lenskart.com", "careers_url": "https://www.lenskart.com/careers"},
    {"company_name": "Cars24", "website_url": "https://www.cars24.com", "careers_url": "https://www.cars24.com/job-openings/"},
    {"company_name": "PhysicsWallah", "website_url": "https://www.pw.live", "careers_url": "https://careers.pw.live/"},
    {"company_name": "Unacademy", "website_url": "https://unacademy.com", "careers_url": "https://unacademy.com/careers"},
    {"company_name": "Scaler", "website_url": "https://www.scaler.com", "careers_url": "https://www.scaler.com/about/careers/"},
    {"company_name": "Coding Ninjas", "website_url": "https://www.codingninjas.com", "careers_url": "https://www.codingninjas.com/careers"},
    {"company_name": "AlmaBetter", "website_url": "https://www.almabetter.com", "careers_url": "https://www.almabetter.com/careers"},
    {"company_name": "Zerodha", "website_url": "https://zerodha.com", "careers_url": "https://zerodha.com/careers/"},
    {"company_name": "Groww", "website_url": "https://groww.in", "careers_url": "https://groww.in/careers"},
    {"company_name": "CoinDCX", "website_url": "https://coindcx.com", "careers_url": "https://coindcx.com/careers"},
    {"company_name": "Smallcase", "website_url": "https://smallcase.com", "careers_url": "https://smallcase.com/careers"},
    {"company_name": "INDmoney", "website_url": "https://www.indmoney.com", "careers_url": "https://www.indmoney.com/careers"},
    {"company_name": "KreditBee", "website_url": "https://www.kreditbee.in", "careers_url": "https://www.kreditbee.in/careers"},
    {"company_name": "Fibe", "website_url": "https://fibe.in", "careers_url": "https://fibe.in/careers"},
    {"company_name": "Slice", "website_url": "https://sliceit.com", "careers_url": "https://sliceit.com/careers"},
    {"company_name": "BharatPe", "website_url": "https://www.bharatpe.com", "careers_url": "https://www.bharatpe.com/careers"},
    {"company_name": "Pine Labs", "website_url": "https://pinelabs.com", "careers_url": "https://pinelabs.com/careers"},
    {"company_name": "Razorpay", "website_url": "https://razorpay.com", "careers_url": "https://razorpay.com/jobs/"},
    {"company_name": "PhonePe", "website_url": "https://www.phonepe.com", "careers_url": "https://www.phonepe.com/careers/"},
    {"company_name": "CRED", "website_url": "https://cred.club", "careers_url": "https://careers.cred.club/"},
    {"company_name": "Urban Company", "website_url": "https://www.urbancompany.com", "careers_url": "https://www.urbancompany.com/careers"},
    {"company_name": "InMobi", "website_url": "https://www.inmobi.com", "careers_url": "https://www.inmobi.com/company/careers/"},
    {"company_name": "Glance", "website_url": "https://www.glance.com", "careers_url": "https://www.glance.com/en-in/career/"},
    {"company_name": "Atlan", "website_url": "https://atlan.com", "careers_url": "https://jobs.lever.co/atlanteam"},
    {"company_name": "Hasura", "website_url": "https://hasura.io", "careers_url": "https://hasura.io/careers/"},
    {"company_name": "SigNoz", "website_url": "https://signoz.io", "careers_url": "https://jobs.ashbyhq.com/SigNoz"},
    {"company_name": "Appwrite", "website_url": "https://appwrite.io", "careers_url": "https://appwrite.io/company/careers"},
    {"company_name": "Kissflow", "website_url": "https://kissflow.com", "careers_url": "https://kissflow.com/careers/"},
    {"company_name": "Ozonetel", "website_url": "https://ozonetel.com", "careers_url": "https://ozonetel.com/careers/"},
    {"company_name": "Shiprocket", "website_url": "https://www.shiprocket.in", "careers_url": "https://www.shiprocket.in/careers/"},
    {"company_name": "Ninjacart", "website_url": "https://ninjacart.com", "careers_url": "https://ninjacart.freshteam.com/jobs"},
    {"company_name": "Locus", "website_url": "https://locus.sh", "careers_url": "https://locus.sh/careers/"},
    {"company_name": "Pixxel", "website_url": "https://www.pixxel.space", "careers_url": "https://www.pixxel.space/careers"},
    {"company_name": "Skyroot Aerospace", "website_url": "https://www.skyroot.in", "careers_url": "https://www.skyroot.in/careers"},
    {"company_name": "Agnikul Cosmos", "website_url": "https://agnikul.in", "careers_url": "https://agnikul.zohorecruit.in/jobs/Careers"},
    {"company_name": "Sarvam AI", "website_url": "https://www.sarvam.ai", "careers_url": "https://www.sarvam.ai/careers"},
    {"company_name": "Krutrim", "website_url": "https://www.olakrutrim.com", "careers_url": "https://www.olakrutrim.com/careers"},
    {"company_name": "Pepper Content", "website_url": "https://www.pepper.inc", "careers_url": "https://peppercontent-talent.freshteam.com/jobs"},
    {"company_name": "WebEngage", "website_url": "https://webengage.com", "careers_url": "https://webengage.com/current-openings/"},
    {"company_name": "MoEngage", "website_url": "https://www.moengage.com", "careers_url": "https://www.moengage.com/careers/"},
    {"company_name": "InVideo", "website_url": "https://invideo.io", "careers_url": "https://jobs.lever.co/invideo"},
    {"company_name": "Shadowfax", "website_url": "https://shadowfax.in", "careers_url": "https://shadowfax.in/careers/"},
    {"company_name": "Droom", "website_url": "https://droom.in", "careers_url": "https://droom.in/info/careers"},
    {"company_name": "Udaan", "website_url": "https://udaan.com", "careers_url": "https://udaan.com/careers.html"},
    {"company_name": "Fynd", "website_url": "https://fynd.com", "careers_url": "https://fynd.com/careers"},
)