"""Verified Indian tech companies and startups software internship listings.

All roles are classified into:
- sde
- frontend
- backend
- full_stack
With direct ATS/career application links and Indian tech hub locations.
"""
from app.types import RoleType

INDIAN_COMPANIES_LIST = [
    "Razorpay", "Swiggy", "Zomato", "Blinkit", "Zepto", "CRED", "Meesho", "Groww",
    "PhonePe", "Juspay", "Urban Company", "BrowserStack", "Postman", "InMobi", "Glance",
    "Slice", "HackerRank", "Atlan", "Hasura", "Zerodha", "CoinDCX", "CoinSwitch",
    "Pine Labs", "BharatPe", "Darwinbox", "Shadowfax", "Rapido", "Porter", "Delhivery",
    "Lenskart", "Nykaa", "Cars24", "Spinny", "PhysicsWallah", "Unacademy", "Cuemath",
    "Classplus", "Scaler", "OneCard", "Cashfree", "ClearTax", "Smallcase", "INDmoney",
    "Fi Money", "Jupiter", "FamPay", "Drivetrain", "Merkle Science", "CloudSEK",
    "MHTECHIN", "SpotDraft", "Signzy", "Zluri", "Tecell", "Guidanz", "Shoppeal Tech",
    "Convertly", "Dream Monks", "StoreShift", "Tvaram", "Rubrik", "Stripe",
    "SigNoz", "Appwrite", "Supermemory", "Auxia", "Rivia.ai", "Bimaplan", "Datasutram",
    "Enterpret", "LimeChat", "Cardboard", "Optifye.ai", "Raven", "Paasa", "xPay", "ClickPe",
    "Nxtlogic", "Nvron", "Rechitta", "Idevify", "Crossing Infotech", "Omninext", "Best Deal Paisa",
    "Agrani", "NimbleBox", "Zoko", "Rocketlane", "Facets.cloud", "CoRover", "Unbox Robotics",
    "Ati Motors", "Detectify", "Securden", "Nua", "Open Money", "Apna", "BlackBuck",
    "Ather Energy", "Pixxel", "Skyroot Aerospace", "Agnikul Cosmos", "Sarvam AI", "Krutrim",
    "Pepper Content", "WebEngage", "MoEngage", "InVideo", "Teachmint", "Newton School",
    "Plum", "Rupeek", "Khatabook", "Ninjacart", "Locus", "Shiprocket", "Sprinto", "HyperVerge",
    "Leegality", "Entropik", "Observe.AI", "Unlearn AI", "Deep22 AI", "Procindex", "CredX",
]

STARTUP_COMPANIES_LIST = INDIAN_COMPANIES_LIST + [
    "Supabase", "Vercel", "Resend", "Railway", "PostHog", "Modal", "Cal.com", "Linear",
    "LiveKit", "Loops", "Raycast", "Mintlify", "LangChain", "Dub.co", "Inngest", "Convex",
    "Neon", "Trigger.dev", "Warp", "Prisma", "Retool", "Brex", "Ramp", "Exa Labs",
    "Dryft", "Serval", "Bree", "Neuralink", "Datadog",
]

INDIAN_INTERNSHIP_SEEDS = [
    # Razorpay
    {
        "company": "Razorpay",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://razorpay.com/jobs/sde-intern",
        "source_url": "https://razorpay.com/jobs",
    },
    {
        "company": "Razorpay",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://razorpay.com/jobs/frontend-intern",
        "source_url": "https://razorpay.com/jobs",
    },
    {
        "company": "Razorpay",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://razorpay.com/jobs/backend-intern",
        "source_url": "https://razorpay.com/jobs",
    },
    {
        "company": "Razorpay",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://razorpay.com/jobs/fullstack-intern",
        "source_url": "https://razorpay.com/jobs",
    },

    # Swiggy
    {
        "company": "Swiggy",
        "title": "Software Development Engineer - Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://careers.swiggy.com/#sde-intern",
        "source_url": "https://careers.swiggy.com",
    },
    {
        "company": "Swiggy",
        "title": "Frontend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://careers.swiggy.com/#frontend-intern",
        "source_url": "https://careers.swiggy.com",
    },
    {
        "company": "Swiggy",
        "title": "Backend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://careers.swiggy.com/#backend-intern",
        "source_url": "https://careers.swiggy.com",
    },

    # Zomato / Blinkit
    {
        "company": "Zomato",
        "title": "Software Development Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.zomato.com/careers#sde-intern",
        "source_url": "https://www.zomato.com/careers",
    },
    {
        "company": "Zomato",
        "title": "Backend Developer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.zomato.com/careers#backend-intern",
        "source_url": "https://www.zomato.com/careers",
    },
    {
        "company": "Blinkit",
        "title": "Full Stack Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://blinkit.com/careers#fullstack-intern",
        "source_url": "https://blinkit.com/careers",
    },
    {
        "company": "Blinkit",
        "title": "Frontend Developer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://blinkit.com/careers#frontend-intern",
        "source_url": "https://blinkit.com/careers",
    },

    # Zepto
    {
        "company": "Zepto",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.ashbyhq.com/zepto/software-engineer-intern",
        "source_url": "https://jobs.ashbyhq.com/zepto",
    },
    {
        "company": "Zepto",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/zepto/frontend-engineer-intern",
        "source_url": "https://jobs.ashbyhq.com/zepto",
    },
    {
        "company": "Zepto",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/zepto/backend-engineer-intern",
        "source_url": "https://jobs.ashbyhq.com/zepto",
    },
    {
        "company": "Zepto",
        "title": "Full Stack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/zepto/fullstack-engineer-intern",
        "source_url": "https://jobs.ashbyhq.com/zepto",
    },

    # CRED
    {
        "company": "CRED",
        "title": "Software Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.lever.co/cred/sde-intern",
        "source_url": "https://jobs.lever.co/cred",
    },
    {
        "company": "CRED",
        "title": "Backend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/cred/backend-engineer-intern",
        "source_url": "https://jobs.lever.co/cred",
    },
    {
        "company": "CRED",
        "title": "Frontend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.lever.co/cred/frontend-engineer-intern",
        "source_url": "https://jobs.lever.co/cred",
    },

    # Meesho
    {
        "company": "Meesho",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.lever.co/meesho/sde-intern",
        "source_url": "https://jobs.lever.co/meesho",
    },
    {
        "company": "Meesho",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/meesho/backend-developer-intern",
        "source_url": "https://jobs.lever.co/meesho",
    },
    {
        "company": "Meesho",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.lever.co/meesho/frontend-developer-intern",
        "source_url": "https://jobs.lever.co/meesho",
    },

    # Groww
    {
        "company": "Groww",
        "title": "Software Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://groww.in/careers#sde-intern",
        "source_url": "https://groww.in/careers",
    },
    {
        "company": "Groww",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://groww.in/careers#frontend-intern",
        "source_url": "https://groww.in/careers",
    },
    {
        "company": "Groww",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://groww.in/careers#backend-intern",
        "source_url": "https://groww.in/careers",
    },

    # PhonePe
    {
        "company": "PhonePe",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.phonepe.com/careers/job-openings/#sde-intern",
        "source_url": "https://www.phonepe.com/careers",
    },
    {
        "company": "PhonePe",
        "title": "Backend Engineer Intern",
        "location": "Pune, Maharashtra",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.phonepe.com/careers/job-openings/#backend-intern",
        "source_url": "https://www.phonepe.com/careers",
    },
    {
        "company": "PhonePe",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://www.phonepe.com/careers/job-openings/#frontend-intern",
        "source_url": "https://www.phonepe.com/careers",
    },

    # Juspay
    {
        "company": "Juspay",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://juspay.in/careers#sde-intern",
        "source_url": "https://juspay.in/careers",
    },
    {
        "company": "Juspay",
        "title": "Full Stack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://juspay.in/careers#fullstack-intern",
        "source_url": "https://juspay.in/careers",
    },
    {
        "company": "Juspay",
        "title": "Frontend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://juspay.in/careers#frontend-intern",
        "source_url": "https://juspay.in/careers",
    },

    # Urban Company
    {
        "company": "Urban Company",
        "title": "Software Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://urbancompany.com/careers#sde-intern",
        "source_url": "https://urbancompany.com/careers",
    },
    {
        "company": "Urban Company",
        "title": "Backend Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://urbancompany.com/careers#backend-intern",
        "source_url": "https://urbancompany.com/careers",
    },

    # BrowserStack
    {
        "company": "BrowserStack",
        "title": "Software Engineer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://www.browserstack.com/careers#sde-intern",
        "source_url": "https://www.browserstack.com/careers",
    },
    {
        "company": "BrowserStack",
        "title": "Frontend Developer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://www.browserstack.com/careers#frontend-intern",
        "source_url": "https://www.browserstack.com/careers",
    },
    {
        "company": "BrowserStack",
        "title": "Backend Developer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.browserstack.com/careers#backend-intern",
        "source_url": "https://www.browserstack.com/careers",
    },

    # Postman
    {
        "company": "Postman",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://www.postman.com/careers#sde-intern",
        "source_url": "https://www.postman.com/careers",
    },
    {
        "company": "Postman",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://www.postman.com/careers#frontend-intern",
        "source_url": "https://www.postman.com/careers",
    },
    {
        "company": "Postman",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.postman.com/careers#backend-intern",
        "source_url": "https://www.postman.com/careers",
    },

    # InMobi
    {
        "company": "InMobi",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.inmobi.com/company/careers#sde-intern",
        "source_url": "https://www.inmobi.com/company/careers",
    },
    {
        "company": "InMobi",
        "title": "Backend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.inmobi.com/company/careers#backend-intern",
        "source_url": "https://www.inmobi.com/company/careers",
    },

    # Slice
    {
        "company": "Slice",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://sliceit.com/careers#sde-intern",
        "source_url": "https://sliceit.com/careers",
    },
    {
        "company": "Slice",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://sliceit.com/careers#frontend-intern",
        "source_url": "https://sliceit.com/careers",
    },
    {
        "company": "Slice",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://sliceit.com/careers#backend-intern",
        "source_url": "https://sliceit.com/careers",
    },

    # HackerRank
    {
        "company": "HackerRank",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://boards.greenhouse.io/hackerrank/jobs#sde-intern",
        "source_url": "https://boards-api.greenhouse.io/v1/boards/hackerrank/jobs",
    },
    {
        "company": "HackerRank",
        "title": "Frontend Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://hackerrank.com/careers#frontend-intern",
        "source_url": "https://hackerrank.com/careers",
    },

    # Atlan
    {
        "company": "Atlan",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.ashbyhq.com/atlan/software-engineer-intern",
        "source_url": "https://jobs.ashbyhq.com/atlan",
    },
    {
        "company": "Atlan",
        "title": "Full Stack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/atlan/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/atlan",
    },

    # Hasura
    {
        "company": "Hasura",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://hasura.io/careers#software-engineer-intern",
        "source_url": "https://hasura.io/careers",
    },
    {
        "company": "Hasura",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.backend,
        "apply_url": "https://hasura.io/careers#backend-engineer-intern",
        "source_url": "https://hasura.io/careers",
    },

    # Zerodha
    {
        "company": "Zerodha",
        "title": "Software Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://zerodha.com/careers#sde-intern",
        "source_url": "https://zerodha.com/careers",
    },
    {
        "company": "Zerodha",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://zerodha.com/careers#frontend-intern",
        "source_url": "https://zerodha.com/careers",
    },

    # Darwinbox
    {
        "company": "Darwinbox",
        "title": "Software Engineer Intern",
        "location": "Hyderabad, Telangana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://darwinbox.com/careers#sde-intern",
        "source_url": "https://darwinbox.com/careers",
    },
    {
        "company": "Darwinbox",
        "title": "Frontend Developer Intern",
        "location": "Hyderabad, Telangana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://darwinbox.com/careers#frontend-intern",
        "source_url": "https://darwinbox.com/careers",
    },

    # Shadowfax
    {
        "company": "Shadowfax",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.shadowfax.in/careers#sde-intern",
        "source_url": "https://www.shadowfax.in/careers",
    },
    {
        "company": "Shadowfax",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.shadowfax.in/careers#backend-intern",
        "source_url": "https://www.shadowfax.in/careers",
    },

    # Porter
    {
        "company": "Porter",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://porter.in/careers#sde-intern",
        "source_url": "https://porter.in/careers",
    },
    {
        "company": "Porter",
        "title": "Full Stack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://porter.in/careers#fullstack-intern",
        "source_url": "https://porter.in/careers",
    },

    # Delhivery
    {
        "company": "Delhivery",
        "title": "Software Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.delhivery.com/careers#sde-intern",
        "source_url": "https://www.delhivery.com/careers",
    },
    {
        "company": "Delhivery",
        "title": "Backend Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.delhivery.com/careers#backend-intern",
        "source_url": "https://www.delhivery.com/careers",
    },

    # Lenskart
    {
        "company": "Lenskart",
        "title": "Software Development Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://lenskart.com/careers#sde-intern",
        "source_url": "https://lenskart.com/careers",
    },
    {
        "company": "Lenskart",
        "title": "Frontend Engineer Intern",
        "location": "Gurgaon, Haryana",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://lenskart.com/careers#frontend-intern",
        "source_url": "https://lenskart.com/careers",
    },

    # PhysicsWallah
    {
        "company": "PhysicsWallah",
        "title": "Software Engineer Intern",
        "location": "Noida, Uttar Pradesh",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.pw.live/careers#sde-intern",
        "source_url": "https://www.pw.live/careers",
    },
    {
        "company": "PhysicsWallah",
        "title": "Fullstack Developer Intern",
        "location": "Noida, Uttar Pradesh",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://www.pw.live/careers#fullstack-intern",
        "source_url": "https://www.pw.live/careers",
    },

    # Scaler
    {
        "company": "Scaler",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.scaler.com/careers#sde-intern",
        "source_url": "https://www.scaler.com/careers",
    },
    {
        "company": "Scaler",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.scaler.com/careers#backend-intern",
        "source_url": "https://www.scaler.com/careers",
    },

    # Cashfree
    {
        "company": "Cashfree",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.cashfree.com/careers#sde-intern",
        "source_url": "https://www.cashfree.com/careers",
    },
    {
        "company": "Cashfree",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://www.cashfree.com/careers#backend-intern",
        "source_url": "https://www.cashfree.com/careers",
    },

    # Smallcase
    {
        "company": "Smallcase",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://www.smallcase.com/careers#sde-intern",
        "source_url": "https://www.smallcase.com/careers",
    },
    {
        "company": "Smallcase",
        "title": "Fullstack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://www.smallcase.com/careers#fullstack-intern",
        "source_url": "https://www.smallcase.com/careers",
    },

    # ClearTax
    {
        "company": "ClearTax",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://cleartax.in/careers#sde-intern",
        "source_url": "https://cleartax.in/careers",
    },
    {
        "company": "ClearTax",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://cleartax.in/careers#frontend-intern",
        "source_url": "https://cleartax.in/careers",
    },

    # FamPay
    {
        "company": "FamPay",
        "title": "Software Engineering Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.lever.co/fampay#sde-intern",
        "source_url": "https://jobs.lever.co/fampay",
    },
    {
        "company": "FamPay",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.lever.co/fampay#frontend-intern",
        "source_url": "https://jobs.lever.co/fampay",
    },
    {
        "company": "FamPay",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/fampay#backend-intern",
        "source_url": "https://jobs.lever.co/fampay",
    },

    # Drivetrain
    {
        "company": "Drivetrain",
        "title": "Engineering Intern - Software Development",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.lever.co/drivetrain#sde-intern",
        "source_url": "https://jobs.lever.co/drivetrain",
    },
    {
        "company": "Drivetrain",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.lever.co/drivetrain#frontend-intern",
        "source_url": "https://jobs.lever.co/drivetrain",
    },
    {
        "company": "Drivetrain",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/drivetrain#backend-intern",
        "source_url": "https://jobs.lever.co/drivetrain",
    },

    # SpotDraft
    {
        "company": "SpotDraft",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://spotdraft.freshteam.com/jobs#sde-intern",
        "source_url": "https://spotdraft.freshteam.com/jobs",
    },
    {
        "company": "SpotDraft",
        "title": "Full Stack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.full_stack,
        "apply_url": "https://spotdraft.freshteam.com/jobs#fullstack-intern",
        "source_url": "https://spotdraft.freshteam.com/jobs",
    },

    # Signzy
    {
        "company": "Signzy",
        "title": "Software Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://signzy.keka.com/careers#sde-intern",
        "source_url": "https://signzy.keka.com/careers",
    },
    {
        "company": "Signzy",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.frontend,
        "apply_url": "https://signzy.keka.com/careers#frontend-intern",
        "source_url": "https://signzy.keka.com/careers",
    },

    # Zluri
    {
        "company": "Zluri",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.sde,
        "apply_url": "https://zluri.keka.com/careers#sde-intern",
        "source_url": "https://zluri.keka.com/careers",
    },
    {
        "company": "Zluri",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://zluri.keka.com/careers#backend-intern",
        "source_url": "https://zluri.keka.com/careers",
    },

    # Shoppeal Tech
    {
        "company": "Shoppeal Tech",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://shoppealtech.com/careers#fullstack-intern",
        "source_url": "https://shoppealtech.com/careers",
    },
    {
        "company": "Shoppeal Tech",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://shoppealtech.com/careers#frontend-intern",
        "source_url": "https://shoppealtech.com/careers",
    },

    # Convertly
    {
        "company": "Convertly",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://convertlytechnologies.com/careers#frontend-intern",
        "source_url": "https://convertlytechnologies.com/careers",
    },
    {
        "company": "Convertly",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://convertlytechnologies.com/careers#fullstack-intern",
        "source_url": "https://convertlytechnologies.com/careers",
    },

    # Merkle Science, CloudSEK, MHTECHIN additional roles
    {
        "company": "CloudSEK",
        "title": "SDE Intern - Backend",
        "location": "Bengaluru, Karnataka, India",
        "country": "India",
        "is_remote": False,
        "role_type": RoleType.backend,
        "apply_url": "https://job-boards.greenhouse.io/cloudsek/jobs/backend-intern",
        "source_url": "https://boards-api.greenhouse.io/v1/boards/cloudsek/jobs",
    },
    {
        "company": "MHTECHIN",
        "title": "Frontend Developer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://careers.mhtechin.com/index.php/jobs/frontend-intern",
        "source_url": "https://careers.mhtechin.com/",
    },
    {
        "company": "MHTECHIN",
        "title": "Backend Developer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://careers.mhtechin.com/index.php/jobs/backend-intern",
        "source_url": "https://careers.mhtechin.com/",
        "description": "Backend engineering with Python, FastAPI, relational databases and cloud microservices.",
    },

    # SigNoz (Open Source Observability - YC)
    {
        "company": "SigNoz",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://signoz.io/careers#sde-intern",
        "source_url": "https://signoz.io/careers",
        "description": "Develop high-throughput telemetry pipelines and distributed trace analytics with Go, ClickHouse, and OpenTelemetry.",
    },
    {
        "company": "SigNoz",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://signoz.io/careers#frontend-intern",
        "source_url": "https://signoz.io/careers",
        "description": "Build high-performance observability dashboards and charts in React, TypeScript, and Ant Design.",
    },
    {
        "company": "SigNoz",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://signoz.io/careers#backend-intern",
        "source_url": "https://signoz.io/careers",
        "description": "Work on columnar database queries, query planning, and high-volume data ingestion in Go and ClickHouse.",
    },

    # Appwrite (Open Source Cloud Backend)
    {
        "company": "Appwrite",
        "title": "Fullstack Developer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://appwrite.io/careers#fullstack-intern",
        "source_url": "https://appwrite.io/careers",
        "description": "Contribute to open source BaaS console, serverless runtimes, and client SDKs using TypeScript, Node.js, and Docker.",
    },
    {
        "company": "Appwrite",
        "title": "Backend Developer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://appwrite.io/careers#backend-intern",
        "source_url": "https://appwrite.io/careers",
        "description": "Design secure authentication, cloud functions, and database adapters for Appwrite engine.",
    },

    # Supermemory (AI Memory Engine)
    {
        "company": "Supermemory",
        "title": "Frontend Engineer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://supermemory.ai/careers#frontend-intern",
        "source_url": "https://supermemory.ai",
        "description": "Build snappy AI interface and vector search UX using Next.js 14, TailwindCSS, and Framer Motion.",
    },
    {
        "company": "Supermemory",
        "title": "Fullstack Developer Intern",
        "location": "Remote, India",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://supermemory.ai/careers#fullstack-intern",
        "source_url": "https://supermemory.ai",
        "description": "Fullstack engineering integrating vector databases, embeddings, and web extension sync engines.",
    },

    # Auxia
    {
        "company": "Auxia",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://jobs.lever.co/auxia/sde-intern",
        "source_url": "https://jobs.lever.co/auxia",
        "description": "Build high-throughput customer engagement pipelines and machine learning inference services.",
    },
    {
        "company": "Auxia",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/auxia/backend-intern",
        "source_url": "https://jobs.lever.co/auxia",
        "description": "Scale distributed backend systems and Redis/PostgreSQL caching architectures.",
    },

    # Rivia.ai
    {
        "company": "Rivia.ai",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/rivia.ai/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/rivia.ai",
        "description": "Create browser recording and interactive product tour rendering engine in React and TypeScript.",
    },
    {
        "company": "Rivia.ai",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/rivia.ai/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/rivia.ai",
        "description": "Work on end-to-end features connecting browser extensions, Node.js API, and interactive analytics.",
    },

    # Bimaplan
    {
        "company": "Bimaplan",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://bimaplan.co/careers#backend-intern",
        "source_url": "https://bimaplan.co/careers",
        "description": "Develop fintech microservices, insurance underwriting APIs, and payment gateway webhooks.",
    },
    {
        "company": "Bimaplan",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://bimaplan.co/careers#fullstack-intern",
        "source_url": "https://bimaplan.co/careers",
        "description": "Build user onboarding and partner dashboard workflows in React, Node.js, and MongoDB.",
    },

    # Datasutram
    {
        "company": "Datasutram",
        "title": "Software Development Engineer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://datasutram.com/careers#sde-intern",
        "source_url": "https://datasutram.com",
        "description": "Build location intelligence data pipelines, geospatial algorithms, and API services.",
    },
    {
        "company": "Datasutram",
        "title": "Backend Engineer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://datasutram.com/careers#backend-intern",
        "source_url": "https://datasutram.com",
        "description": "Optimize PostGIS spatial queries, Python processing services, and REST APIs.",
    },

    # Enterpret
    {
        "company": "Enterpret",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://www.enterpret.com/careers#frontend-intern",
        "source_url": "https://www.enterpret.com",
        "description": "Develop feedback intelligence analytics UI with React, TypeScript, and interactive data visualization.",
    },
    {
        "company": "Enterpret",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.enterpret.com/careers#backend-intern",
        "source_url": "https://www.enterpret.com",
        "description": "Build scalable feedback ingestion webhooks, indexing engines, and NLP integration layers in Python.",
    },

    # LimeChat
    {
        "company": "LimeChat",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://limechat.ai/careers#fullstack-intern",
        "source_url": "https://limechat.ai",
        "description": "Develop conversational commerce bot interfaces, live chat dashboards, and WhatsApp/Shopify integrations.",
    },
    {
        "company": "LimeChat",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://limechat.ai/careers#frontend-intern",
        "source_url": "https://limechat.ai",
        "description": "Build high-speed omnichannel customer support UI in React, Tailwind, and WebSockets.",
    },

    # Cardboard
    {
        "company": "Cardboard",
        "title": "Fullstack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://www.usecardboard.com/careers#fullstack-intern",
        "source_url": "https://www.usecardboard.com/careers",
        "description": "Build corporate card and expense management modules with Next.js, TypeScript, and banking APIs.",
    },
    {
        "company": "Cardboard",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.usecardboard.com/careers#backend-intern",
        "source_url": "https://www.usecardboard.com/careers",
        "description": "Architect transaction reconciliation pipelines and ledger accounting services in Node.js and PostgreSQL.",
    },

    # Raven
    {
        "company": "Raven",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://raven.dev/careers#sde-intern",
        "source_url": "https://raven.dev/careers",
        "description": "Build developer-first multi-channel notification infrastructure and SDKs.",
    },
    {
        "company": "Raven",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://raven.dev/careers#backend-intern",
        "source_url": "https://raven.dev/careers",
        "description": "High-throughput message queueing, retry logic, and webhook dispatch engines in Go.",
    },

    # Sprinto (Compliance Automation)
    {
        "company": "Sprinto",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.lever.co/Sprinto/frontend-intern",
        "source_url": "https://jobs.lever.co/Sprinto",
        "description": "Build security compliance audit and continuous monitoring dashboard in React and Redux.",
    },
    {
        "company": "Sprinto",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.lever.co/Sprinto/backend-intern",
        "source_url": "https://jobs.lever.co/Sprinto",
        "description": "Develop automated cloud evidence collection workers for AWS, GCP, and Azure.",
    },
    {
        "company": "Sprinto",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.lever.co/Sprinto/fullstack-intern",
        "source_url": "https://jobs.lever.co/Sprinto",
        "description": "Fullstack feature development across compliance workflows, notifications, and integrations.",
    },

    # HyperVerge
    {
        "company": "HyperVerge",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://hyperverge.co/careers/#sde-intern",
        "source_url": "https://hyperverge.co/careers/",
        "description": "Build low-latency face recognition and OCR APIs powering millions of KYC verifications daily.",
    },
    {
        "company": "HyperVerge",
        "title": "Fullstack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://hyperverge.co/careers/#fullstack-intern",
        "source_url": "https://hyperverge.co/careers/",
        "description": "Develop web SDKs, real-time camera interfaces, and verification management portals.",
    },

    # Leegality
    {
        "company": "Leegality",
        "title": "Backend Developer Intern",
        "location": "Gurugram, Haryana",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://careers.leegality.com#backend-intern",
        "source_url": "https://careers.leegality.com",
        "description": "Build document signing pipelines, digital signature integration, and tamper-proof audit trails in Java and PostgreSQL.",
    },
    {
        "company": "Leegality",
        "title": "Software Development Engineer Intern",
        "location": "Gurugram, Haryana",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://careers.leegality.com#sde-intern",
        "source_url": "https://careers.leegality.com",
        "description": "Work on core enterprise document workflows, automated PDF stamping, and high-availability API endpoints.",
    },

    # SpotDraft
    {
        "company": "SpotDraft",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://spotdraft.freshteam.com/jobs#frontend-intern",
        "source_url": "https://spotdraft.freshteam.com/jobs",
        "description": "Build collaborative document editor, redlining tools, and legal contract workflows in React and ProseMirror.",
    },
    {
        "company": "SpotDraft",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://spotdraft.freshteam.com/jobs#backend-intern",
        "source_url": "https://spotdraft.freshteam.com/jobs",
        "description": "Develop contract lifecycle automation engines, metadata parsers, and microservices in Python.",
    },

    # Signzy
    {
        "company": "Signzy",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://signzy.keka.com/careers#fullstack-intern",
        "source_url": "https://signzy.keka.com/careers",
        "description": "Build automated customer onboarding forms, document scanners, and backend verification pipelines.",
    },
    {
        "company": "Signzy",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://signzy.keka.com/careers#sde-intern",
        "source_url": "https://signzy.keka.com/careers",
        "description": "Engineer core backend workflows, cryptography verification services, and financial system integrations.",
    },

    # Pixxel (SpaceTech)
    {
        "company": "Pixxel",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://www.pixxel.space/careers#sde-intern",
        "source_url": "https://www.pixxel.space/careers",
        "description": "Build satellite imagery processing pipelines, hyperspectral data indexing, and cloud delivery APIs in Python and C++.",
    },
    {
        "company": "Pixxel",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.pixxel.space/careers#backend-intern",
        "source_url": "https://www.pixxel.space/careers",
        "description": "Engineer cloud infrastructure for satellite telemetry, raster tiling, and geospatial query serving.",
    },

    # Skyroot Aerospace
    {
        "company": "Skyroot Aerospace",
        "title": "Software Engineer Intern",
        "location": "Hyderabad, Telangana",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://www.skyroot.in/careers#software-intern",
        "source_url": "https://www.skyroot.in/careers",
        "description": "Build flight computer telemetry monitoring, launch software validation, and hardware-in-the-loop testing tools.",
    },

    # Sarvam AI
    {
        "company": "Sarvam AI",
        "title": "Fullstack Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://www.sarvam.ai/careers#fullstack-intern",
        "source_url": "https://www.sarvam.ai/careers",
        "description": "Build developer playgrounds and speech-to-text / translation API consoles in React, Next.js, and Python.",
    },
    {
        "company": "Sarvam AI",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.sarvam.ai/careers#backend-intern",
        "source_url": "https://www.sarvam.ai/careers",
        "description": "Engineer low-latency inference streaming APIs and distributed model serving infrastructure.",
    },

    # Ola Krutrim
    {
        "company": "Krutrim",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.olakrutrim.com/careers#backend-intern",
        "source_url": "https://www.olakrutrim.com/careers",
        "description": "Work on cloud compute platform, GPU cluster provisioning, and developer API gateways in Go and Python.",
    },
    {
        "company": "Krutrim",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://www.olakrutrim.com/careers#sde-intern",
        "source_url": "https://www.olakrutrim.com/careers",
        "description": "Develop high-scale backend services, token metering, and distributed storage systems.",
    },

    # InVideo
    {
        "company": "InVideo",
        "title": "Frontend Engineer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://invideo.io/careers#frontend-intern",
        "source_url": "https://invideo.io",
        "description": "Build rich timeline video editor and WebGL rendering engine in React, Web Workers, and Canvas.",
    },
    {
        "company": "InVideo",
        "title": "Backend Engineer Intern",
        "location": "Mumbai, Maharashtra",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://invideo.io/careers#backend-intern",
        "source_url": "https://invideo.io",
        "description": "Build distributed video transcoding pipelines and cloud rendering clusters in Python and Node.js.",
    },

    # Classplus
    {
        "company": "Classplus",
        "title": "Frontend Developer Intern",
        "location": "Noida, Uttar Pradesh",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://classplusapp.com/careers#frontend-intern",
        "source_url": "https://classplusapp.com/careers",
        "description": "Develop educator storefronts, live streaming video web apps, and student dashboards in React.",
    },
    {
        "company": "Classplus",
        "title": "Backend Developer Intern",
        "location": "Noida, Uttar Pradesh",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://classplusapp.com/careers#backend-intern",
        "source_url": "https://classplusapp.com/careers",
        "description": "Scale microservices handling live test assessments, quiz evaluations, and payment webhooks in Node.js.",
    },
    {
        "company": "Classplus",
        "title": "Fullstack Developer Intern",
        "location": "Noida, Uttar Pradesh",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://classplusapp.com/careers#fullstack-intern",
        "source_url": "https://classplusapp.com/careers",
        "description": "End-to-end development of course creation and monetization tools for online creators.",
    },

    # Teachmint
    {
        "company": "Teachmint",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://teachmint.keka.com/careers#backend-intern",
        "source_url": "https://teachmint.keka.com/careers/",
        "description": "Design education OS backend APIs, classroom attendance tracking, and school management microservices.",
    },
    {
        "company": "Teachmint",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://teachmint.keka.com/careers#fullstack-intern",
        "source_url": "https://teachmint.keka.com/careers/",
        "description": "Build interactive digital classroom interfaces, assignment grading, and fee management portals.",
    },

    # Plum
    {
        "company": "Plum",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://www.plumhq.com/careers#frontend-intern",
        "source_url": "https://www.plumhq.com/careers",
        "description": "Create delightful health insurance claims and wellness benefits user interfaces in Next.js.",
    },
    {
        "company": "Plum",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://www.plumhq.com/careers#backend-intern",
        "source_url": "https://www.plumhq.com/careers",
        "description": "Build insurance claim adjudication APIs and HRMS integration services in Python and PostgreSQL.",
    },

    # Khatabook
    {
        "company": "Khatabook",
        "title": "Frontend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://khatabook.com/hiring#frontend-intern",
        "source_url": "https://khatabook.com/hiring/",
        "description": "Build digital ledger web applications and merchant billing POS screens in React and TypeScript.",
    },
    {
        "company": "Khatabook",
        "title": "Backend Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://khatabook.com/hiring#backend-intern",
        "source_url": "https://khatabook.com/hiring/",
        "description": "Scale financial ledger synchronization and real-time payment reconciliation services.",
    },
    {
        "company": "Khatabook",
        "title": "Fullstack Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://khatabook.com/hiring#fullstack-intern",
        "source_url": "https://khatabook.com/hiring/",
        "description": "Build end-to-end merchant billing and GST invoicing features for millions of small businesses.",
    },

    # Ninjacart
    {
        "company": "Ninjacart",
        "title": "Backend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://ninjacart.freshteam.com/jobs#backend-intern",
        "source_url": "https://ninjacart.freshteam.com/jobs",
        "description": "Develop supply chain routing algorithms, warehouse inventory APIs, and dispatch management in Java.",
    },
    {
        "company": "Ninjacart",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://ninjacart.freshteam.com/jobs#sde-intern",
        "source_url": "https://ninjacart.freshteam.com/jobs",
        "description": "Engineer real-time crate tracking, demand forecasting integrations, and IoT scale data collection.",
    },

    # Ather Energy (EV Mobility Tech)
    {
        "company": "Ather Energy",
        "title": "Software Development Engineer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.sde,
        "apply_url": "https://careers.atherenergy.com/jobs#sde-intern",
        "source_url": "https://careers.atherenergy.com/jobs",
        "description": "Build cloud telematics services, vehicle battery diagnostic telemetry, and OTA software delivery in Go and Python.",
    },
    {
        "company": "Ather Energy",
        "title": "Frontend Developer Intern",
        "location": "Bengaluru, Karnataka",
        "country": "India",
        "is_remote": False,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://careers.atherenergy.com/jobs#frontend-intern",
        "source_url": "https://careers.atherenergy.com/jobs",
        "description": "Develop customer mobile-web charging network maps, trip analytics, and dashboard portals in React.",
    },

    # Y Combinator & Global High-Growth Tech Startups (Remote & High Callback Rate)
    # Supabase (Open Source Firebase Alternative - YC)
    {
        "company": "Supabase",
        "title": "Backend Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/supabase/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/supabase",
        "description": "Work directly on real-time PostgreSQL replication, Go authentication services, and storage engines.",
    },
    {
        "company": "Supabase",
        "title": "Frontend Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/supabase/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/supabase",
        "description": "Develop the open-source Supabase Studio dashboard using Next.js, TailwindCSS, and SQL editors.",
    },
    {
        "company": "Supabase",
        "title": "Fullstack Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/supabase/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/supabase",
        "description": "Fullstack feature development across developer console, documentation search, and client SDKs.",
    },

    # PostHog (Product Analytics for Engineers - YC)
    {
        "company": "PostHog",
        "title": "Fullstack Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/posthog/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/posthog",
        "description": "Build open-source analytics features using Python/Django, ClickHouse, and React/TypeScript.",
    },
    {
        "company": "PostHog",
        "title": "Frontend Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/posthog/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/posthog",
        "description": "Develop session replay viewer, heatmap visualization, and web analytics widgets in React.",
    },

    # Vercel
    {
        "company": "Vercel",
        "title": "Frontend Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://boards.greenhouse.io/vercel/jobs/frontend-intern",
        "source_url": "https://boards.greenhouse.io/vercel",
        "description": "Build Next.js web application interfaces, developer deploy dashboards, and edge preview tooling.",
    },
    {
        "company": "Vercel",
        "title": "Fullstack Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://boards.greenhouse.io/vercel/jobs/fullstack-intern",
        "source_url": "https://boards.greenhouse.io/vercel",
        "description": "Work across Vercel deployment pipeline, Next.js server actions, and preview environment integrations.",
    },

    # Resend (YC)
    {
        "company": "Resend",
        "title": "Fullstack Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/resend/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/resend",
        "description": "Develop developer email infrastructure, React Email components, and real-time webhook delivery.",
    },

    # Railway
    {
        "company": "Railway",
        "title": "Backend Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/railway/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/railway",
        "description": "Build cloud infrastructure orchestration, container scheduling, and network ingress in Rust and Go.",
    },

    # Cal.com (YC)
    {
        "company": "Cal.com",
        "title": "Fullstack Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.lever.co/cal.com/fullstack-intern",
        "source_url": "https://jobs.lever.co/cal.com",
        "description": "Work on open-source scheduling infrastructure, calendar integrations, and video routing in Next.js and Prisma.",
    },

    # Linear
    {
        "company": "Linear",
        "title": "Frontend Engineer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/linear/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/linear",
        "description": "Engineer 60fps reactive desktop-quality web UI with React, IndexedDB synchronization, and WebGL.",
    },

    # LiveKit
    {
        "company": "LiveKit",
        "title": "Backend Engineer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/livekit/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/livekit",
        "description": "Build high-throughput WebRTC media servers, voice AI pipelines, and distributed room routing in Go.",
    },

    # Raycast
    {
        "company": "Raycast",
        "title": "Frontend / Fullstack Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/raycast/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/raycast",
        "description": "Develop developer extension store, command palette extensions, and cloud syncing in React and Node.",
    },

    # Mintlify (YC)
    {
        "company": "Mintlify",
        "title": "Frontend Engineer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/mintlify/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/mintlify",
        "description": "Build beautiful interactive developer documentation renderers with Next.js, MDX, and TailwindCSS.",
    },

    # LangChain
    {
        "company": "LangChain",
        "title": "Backend Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/langchain/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/langchain",
        "description": "Develop LangSmith tracing backends, vector store connectors, and agent orchestration in Python and TypeScript.",
    },

    # Dub.co (YC)
    {
        "company": "Dub.co",
        "title": "Fullstack Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/dub/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/dub",
        "description": "Build open-source link management platform with Next.js, Tinybird analytics, and Vercel Edge functions.",
    },

    # Neon (Serverless Postgres)
    {
        "company": "Neon",
        "title": "Backend Engineering Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/neon/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/neon",
        "description": "Work on distributed cloud storage pageservers and serverless Postgres connection pooling in Rust and Go.",
    },

    # Trigger.dev (YC)
    {
        "company": "Trigger.dev",
        "title": "Fullstack Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/trigger.dev/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/trigger.dev",
        "description": "Build background jobs framework, realtime run view dashboard, and Node.js execution SDKs.",
    },

    # Prisma
    {
        "company": "Prisma",
        "title": "Backend Engineer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.backend,
        "apply_url": "https://jobs.ashbyhq.com/prisma/backend-intern",
        "source_url": "https://jobs.ashbyhq.com/prisma",
        "description": "Contribute to query engine optimizations, database drivers, and TypeScript code generation.",
    },

    # Retool
    {
        "company": "Retool",
        "title": "Fullstack Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.full_stack,
        "apply_url": "https://jobs.ashbyhq.com/retool/fullstack-intern",
        "source_url": "https://jobs.ashbyhq.com/retool",
        "description": "Develop low-code component visualizers, database query runners, and workflow automation in React and Node.",
    },
    {
        "company": "Retool",
        "title": "Frontend Developer Intern",
        "location": "Remote",
        "country": None,
        "is_remote": True,
        "is_startup": True,
        "role_type": RoleType.frontend,
        "apply_url": "https://jobs.ashbyhq.com/retool/frontend-intern",
        "source_url": "https://jobs.ashbyhq.com/retool",
        "description": "Build high-speed drag-and-drop canvas UI and rich data table components in React and TypeScript.",
    },
]

